#!/bin/bash -ex

echo "Starting backup..."

mkdir -p /data/backups/full

. /data/env
export PGDATABASE=${POSTGRESQL_DB}
export PGPASSWORD=${POSTGRESQL_PASS}
pg_dump \
    --host=localhost \
    --username=${POSTGRESQL_USER} \
    --file=/data/backups/full/backup_postgres_${POSTGRESQL_DB}_$(date --utc --iso-8601=ns).sql
